FROM node:22-alpine

WORKDIR /app
COPY . .

RUN npm install

ARG NODE_ENV=production
ARG BASE_PATH=$BASE_PATH
ARG SCOPE_URL=$SCOPE_URL
ARG TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
ARG TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID

CMD ["node", "src/app.js"]
